// src/Login.vue
<template lang="jade">
	div
		.section
			.logo
				img(src="./assets/logo.png")
			.box(v-on:keyup.enter="Login(account,pass)")
				.title 用户登录
				ui-textbox(v-bind:value.sync="account" name="account" label="用户名" placeholder="account" icon="person_outline")
				ui-textbox(v-bind:value.sync="pass" name="password" label="密码" placeholder="password" type="password" icon="vpn_key")
				ui-button(color="primary" v-on:click="Login(account,pass)") 登录
</template>
<script>
	import {login,getInfo} from './store/user'
	import store from 'store'
	export default {
		data(){
			return {
				account:"",
				pass:"",
			}
		},
		components:{
			'ui-textbox':require('keen-ui/lib/UiTextbox'),
			'ui-button':require('keen-ui/lib/UiButton')
		},
		vuex:{
			actions:{
				async Login({dispatch},account,pass){
					try{
						var token=await login(account,pass)
					}catch(err){
						return this.$dispatch("toast",err,"error")
					}
					store.set("token",token)
					this.$dispatch("toast","登录成功","success")
					try{
						var info=await getInfo(token)
					}catch(err){
						return this.$dispatch("toast",err,"error")
					}
					dispatch("SET_USER",info)
					this.$route.router.go({path:"/"})
				},
			}
		}
	}
</script>
<style lang="stylus" scoped>
	.section
		width:1000px;margin:0 auto;position:relative
	.logo
		position: absolute;top:200px;left:130px
		img
			width:260px;height:260px
	.box
		border: 1px solid #ededed;width: 300px;padding:20px 40px 40px 40px;position: absolute;right: 150px;
		top: 200px;background: #FFFFFF;box-shadow: 0 0 25px rgba(187,196,205,0.1);
		font-family: "Microsoft YaHei";font-size: 14px
		.title
			font-size:20px;text-align:center;border-bottom:1px solid;margin-bottom:20px;line-height:2;
			color:#2196f3
		.ui-button
			width:100%
</style>

// src/main/login.jsx
import React,{Component} from 'react'
import Radium from 'radium'
import {Link,browserHistory} from 'react-router'
import store from 'store'
import InfoBox from '../components/InfoBox'

import Input from '../lib/Input'
// import Lock from '../lib/Linearicons/Lock'
// import Smile from '../lib/Linearicons/Smile'
// import Sad from '../lib/Linearicons/Sad'
import Icon from '../lib/Icon'
import Button from '../lib/Button'
import Ajax from '../lib/Ajax'
import FormGroup from '../lib/FormGroup'

@Radium
class LoginPanel extends Component{
	state={account:"",pass:""}
	render(){
		var {account,pass}=this.state
		return (
			<div onKeyDown={event=>{if(event.keyCode==13)this.refs.post.request()}} style={[{padding:40,border:"1px solid #ccc",float:"right"},this.props.style]}>
				<FormGroup>
					<Input addLeft={account.length!=11&&account.length!=0?<Icon name="sentiment_dissatisfied" />:<Icon name="sentiment_satisfied" />} size="lg" full
						color={account.length==0?"default":(account.length!=11?"danger":"success")} 
						onChange={e=>this.setState({account:e.target.value})} />
				</FormGroup>
				<FormGroup>
					<Input addLeft={<Icon name="lock" />} type="password" size="lg" full
						color={pass.length==0?"default":(pass.length>=6&&pass.length<=30?"success":"danger")} 
						onChange={e=>this.setState({pass:e.target.value})}  />
				</FormGroup>
				<p style={{margin:30}}>
					<Link to="#">忘记密码？</Link>
					<Link to="/register.html" style={{float:"right"}}>注册</Link>
				</p>
				<Button full size="xl" onClick={()=>this.refs.post.request()}>登录</Button>
				<Ajax ref="post" method="post" url={"/users/auth"} data={JSON.stringify({account,pass})} onSuccess={data=>{
					store.set('token',data.token)
					browserHistory.push("/")
				}} alert />
			</div>
		)
	}
}

export default class extends Component{
	render(){
		return(
			<InfoBox title="登录">
				<div style={{height:700,width:1000,margin:"0 auto",padding:"150px 100px"}}>
					<div style={{width:350,height:350,float:"left"}}>
						<img src={require("./logo.png")} style={{width:"100%",height:"100%"}} />
					</div>
					<LoginPanel style={{width:440,height:350,float:"right"}} />
				</div>
			</InfoBox>
		)
	}
}
